# This is a basic workflow to help you get started with Actions

name: Push to main
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
    steps:
      - run: echo "Branch ${{ github.repository }} has new features"
      - name: Checkout code
        uses: actions/checkout@v3
      - run: echo "Branch ${{ github.repository }} checkedout"
